apiVersion: skaffold/v4beta6
kind: Config
build:
  artifacts:
    - image: tons/rutineret-web
      docker:
        buildArgs:
          VITE_API_URL: "{{ .VITE_API_URL }}"
deploy:
  helm:
    releases:
      - name: rutineret-web
        namespace: rutineret
        createNamespace: true
        chartPath: charts/rutineret-web
        setValueTemplates:
          ingress:
            enabled: true
            hosts:
              - host: "{{ .VITE_ENVIRONMENT }}rutineret.c.th.fitfit.dk"
                paths:
                  - path: /
                    pathType: ImplementationSpecific
