apiVersion: skaffold/v4beta6
kind: Config
build:
  artifacts:
    - image: tons/rutineret-web
      docker:
        buildArgs:
          API_BASE_URL: "{{ .VITE_API_BASE_URL }}"
deploy:
  helm:
    releases:
      - name: rutineret-web
        namespace: rutineret
        createNamespace: true
        chartPath: charts/rutineret-web
#        setValueTemplates:
#          ingress:
#            enabled: true
#            hostname: "{{ .UI_HOSTNAME }}"
#            certIssuer: cert-issuer-prod
#        valuesFiles:
#          - helm/data/values/{{ .CLASSIFICATION }}/values.yaml
