apiVersion: skaffold/v4beta6
kind: Config
build:
  artifacts:
    - image: tons/rutineret-web
      docker:
        buildArgs:
          VITE_API_URL: "{{ .VITE_API_URL }}"
deploy:
  helm:
    releases:
      - name: rutineret-web
        namespace: "rutineret-{{ .VITE_ENVIRONMENT }}"
        createNamespace: true
        chartPath: charts/rutineret-web
        setValueTemplates:
          ingress:
            enabled: true
            hosts:
              - host: "{{ .HOST }}"
                paths:
                  - path: /
                    pathType: ImplementationSpecific

profiles:
  - name: always-pull
    patches:
      - op: add
        path: /deploy/helm/releases/0/setValueTemplates/image.pullPolicy
        value: "Always"
